--- #YAML:1.0
name:               SQL-Statement
version:            1.21_3
abstract:           ~
author:
    - Jeff Zucker <jeff@vpservices.com>, Jens Rehsack <rehsack@web.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Clone:         0.30
    Params::Util:  0.35
    Scalar::Util:  1.0
    Test::Simple:  0.86
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
